"""add citation_token to messages

Revision ID: 66bb74b53ffb
Revises: f051aa0cbb8e
Create Date: 2026-02-14 14:40:00.030764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66bb74b53ffb'
down_revision = 'f051aa0cbb8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('citation_token', sa.String(length=12), nullable=True))
        batch_op.create_unique_constraint(None, ['citation_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('citation_token')

    # ### end Alembic commands ###
